import Reagent from "../classes/Reagent"

const CREATED = new Date("2026-02-01T14:30:00Z")

export default function getReagents(): Reagent[] {
  return [
    new Reagent({
      id: "R-001",
      type: "reagent",
      name: "water",
      created: CREATED,
      density: 0.99997,
      alias: "H2O",
      costPerGram: 0.000001,
      costUnit: "$",
      state: "liquid",
      description: "Deionised laboratory water",
      hazards: [],
      molecularWeight: 18.01528,
      smiles: "O",
      chemicalFormula: "H2O",
      CASNumber: "7732-18-5",
      supplier: "internal",
      purity: 1.0,
    }),

    new Reagent({
      id: "R-002",
      type: "reagent",
      name: "ethanol",
      created: CREATED,
      density: 0.789,
      alias: "EtOH",
      costPerGram: 0.0012,
      costUnit: "$",
      state: "liquid",
      description: "Absolute ethanol, anhydrous",
      hazards: ["H225", "H319"],
      molecularWeight: 46.07,
      smiles: "CCO",
      chemicalFormula: "C2H6O",
      CASNumber: "64-17-5",
      supplier: "Sigma-Aldrich",
      purity: 0.999,
    }),

    new Reagent({
      id: "R-003",
      type: "reagent",
      name: "acetone",
      created: CREATED,
      density: 0.7845,
      alias: "acetone",
      costPerGram: 0.0009,
      costUnit: "$",
      state: "liquid",
      description: "Analytical grade acetone",
      hazards: ["H225", "H319", "H336"],
      molecularWeight: 58.08,
      smiles: "CC(=O)C",
      chemicalFormula: "C3H6O",
      CASNumber: "67-64-1",
      supplier: "Fisher Scientific",
      purity: 0.995,
    }),

    new Reagent({
      id: "R-004",
      type: "reagent",
      name: "sodium chloride",
      created: CREATED,
      density: 2.165,
      alias: "NaCl",
      costPerGram: 0.0003,
      costUnit: "$",
      state: "solid",
      description: "Laboratory grade sodium chloride",
      hazards: [],
      molecularWeight: 58.44,
      smiles: "[Na+].[Cl-]",
      chemicalFormula: "NaCl",
      CASNumber: "7647-14-5",
      supplier: "Merck",
      purity: 0.99,
    }),

    new Reagent({
      id: "R-005",
      type: "reagent",
      name: "hydrochloric acid",
      created: CREATED,
      density: 1.19,
      alias: "HCl",
      costPerGram: 0.0025,
      costUnit: "$",
      state: "liquid",
      description: "37% aqueous hydrochloric acid",
      hazards: ["H290", "H314"],
      molecularWeight: 36.46,
      smiles: "Cl",
      chemicalFormula: "HCl",
      CASNumber: "7647-01-0",
      supplier: "Sigma-Aldrich",
      purity: 0.37,
    }),

    new Reagent({
      id: "R-006",
      type: "reagent",
      name: "sodium hydroxide",
      created: CREATED,
      density: 2.13,
      alias: "NaOH",
      costPerGram: 0.0015,
      costUnit: "$",
      state: "solid",
      description: "Pellet sodium hydroxide",
      hazards: ["H314"],
      molecularWeight: 40.0,
      smiles: "[Na+].[OH-]",
      chemicalFormula: "NaOH",
      CASNumber: "1310-73-2",
      supplier: "Fisher Scientific",
      purity: 0.98,
    }),

    new Reagent({
      id: "R-007",
      type: "reagent",
      name: "methanol",
      created: CREATED,
      density: 0.792,
      alias: "MeOH",
      costPerGram: 0.0008,
      costUnit: "$",
      state: "liquid",
      description: "HPLC grade methanol",
      hazards: ["H225", "H301", "H311", "H331", "H370"],
      molecularWeight: 32.04,
      smiles: "CO",
      chemicalFormula: "CH4O",
      CASNumber: "67-56-1",
      supplier: "Sigma-Aldrich",
      purity: 0.999,
    }),

    new Reagent({
      id: "R-008",
      type: "reagent",
      name: "isopropanol",
      created: CREATED,
      density: 0.786,
      alias: "IPA",
      costPerGram: 0.0007,
      costUnit: "$",
      state: "liquid",
      description: "Isopropyl alcohol, laboratory grade",
      hazards: ["H225", "H319", "H336"],
      molecularWeight: 60.1,
      smiles: "CC(C)O",
      chemicalFormula: "C3H8O",
      CASNumber: "67-63-0",
      supplier: "Fisher Scientific",
      purity: 0.995,
    }),

    new Reagent({
      id: "R-009",
      type: "reagent",
      name: "dimethyl sulfoxide",
      created: CREATED,
      density: 1.1,
      alias: "DMSO",
      costPerGram: 0.002,
      costUnit: "$",
      state: "liquid",
      description: "Anhydrous dimethyl sulfoxide",
      hazards: ["H227"],
      molecularWeight: 78.13,
      smiles: "CS(C)=O",
      chemicalFormula: "C2H6OS",
      CASNumber: "67-68-5",
      supplier: "Sigma-Aldrich",
      purity: 0.999,
    }),

    new Reagent({
      id: "R-010",
      type: "reagent",
      name: "dichloromethane",
      created: CREATED,
      density: 1.325,
      alias: "DCM",
      costPerGram: 0.0018,
      costUnit: "$",
      state: "liquid",
      description: "Dichloromethane, stabilised",
      hazards: ["H315", "H319", "H335", "H351"],
      molecularWeight: 84.93,
      smiles: "ClCCl",
      chemicalFormula: "CH2Cl2",
      CASNumber: "75-09-2",
      supplier: "Merck",
      purity: 0.995,
    }),

    new Reagent({
      id: "R-011",
      type: "reagent",
      name: "chloroform",
      created: CREATED,
      density: 1.489,
      alias: "CHCl3",
      costPerGram: 0.0022,
      costUnit: "$",
      state: "liquid",
      description: "Chloroform, amylene-stabilised",
      hazards: ["H302", "H315", "H319", "H351", "H373"],
      molecularWeight: 119.38,
      smiles: "ClC(Cl)Cl",
      chemicalFormula: "CHCl3",
      CASNumber: "67-66-3",
      supplier: "Sigma-Aldrich",
      purity: 0.99,
    }),

    new Reagent({
      id: "R-012",
      type: "reagent",
      name: "ethyl acetate",
      created: CREATED,
      density: 0.902,
      alias: "EtOAc",
      costPerGram: 0.001,
      costUnit: "$",
      state: "liquid",
      description: "Ethyl acetate, laboratory grade",
      hazards: ["H225", "H319", "H336"],
      molecularWeight: 88.11,
      smiles: "CCOC(=O)C",
      chemicalFormula: "C4H8O2",
      CASNumber: "141-78-6",
      supplier: "Fisher Scientific",
      purity: 0.995,
    }),

    new Reagent({
      id: "R-013",
      type: "reagent",
      name: "hexane",
      created: CREATED,
      density: 0.659,
      alias: "n-hexane",
      costPerGram: 0.0011,
      costUnit: "$",
      state: "liquid",
      description: "n-Hexane, 95% min",
      hazards: ["H225", "H304", "H315", "H336", "H373", "H411"],
      molecularWeight: 86.18,
      smiles: "CCCCCC",
      chemicalFormula: "C6H14",
      CASNumber: "110-54-3",
      supplier: "Merck",
      purity: 0.95,
    }),

    new Reagent({
      id: "R-014",
      type: "reagent",
      name: "toluene",
      created: CREATED,
      density: 0.867,
      alias: "toluene",
      costPerGram: 0.0013,
      costUnit: "$",
      state: "liquid",
      description: "Toluene, laboratory grade",
      hazards: ["H225", "H304", "H315", "H336", "H373"],
      molecularWeight: 92.14,
      smiles: "Cc1ccccc1",
      chemicalFormula: "C7H8",
      CASNumber: "108-88-3",
      supplier: "Sigma-Aldrich",
      purity: 0.995,
    }),

    new Reagent({
      id: "R-015",
      type: "reagent",
      name: "tetrahydrofuran",
      created: CREATED,
      density: 0.889,
      alias: "THF",
      costPerGram: 0.0016,
      costUnit: "$",
      state: "liquid",
      description: "Tetrahydrofuran, inhibitor-free",
      hazards: ["H225", "H319", "H335"],
      molecularWeight: 72.11,
      smiles: "C1CCOC1",
      chemicalFormula: "C4H8O",
      CASNumber: "109-99-9",
      supplier: "Fisher Scientific",
      purity: 0.995,
    }),

    new Reagent({
      id: "R-016",
      type: "reagent",
      name: "dimethylformamide",
      created: CREATED,
      density: 0.944,
      alias: "DMF",
      costPerGram: 0.0014,
      costUnit: "$",
      state: "liquid",
      description: "N,N-Dimethylformamide, anhydrous",
      hazards: ["H226", "H312", "H332", "H360D"],
      molecularWeight: 73.09,
      smiles: "CN(C)C=O",
      chemicalFormula: "C3H7NO",
      CASNumber: "68-12-2",
      supplier: "Sigma-Aldrich",
      purity: 0.995,
    }),

    new Reagent({
      id: "R-017",
      type: "reagent",
      name: "acetonitrile",
      created: CREATED,
      density: 0.786,
      alias: "ACN",
      costPerGram: 0.0017,
      costUnit: "$",
      state: "liquid",
      description: "HPLC grade acetonitrile",
      hazards: ["H225", "H302", "H312", "H319", "H332"],
      molecularWeight: 41.05,
      smiles: "CC#N",
      chemicalFormula: "C2H3N",
      CASNumber: "75-05-8",
      supplier: "Merck",
      purity: 0.999,
    }),

    new Reagent({
      id: "R-018",
      type: "reagent",
      name: "sulfuric acid",
      created: CREATED,
      density: 1.84,
      alias: "H2SO4",
      costPerGram: 0.001,
      costUnit: "$",
      state: "liquid",
      description: "Concentrated sulfuric acid (~98% w/w)",
      hazards: ["H290", "H314"],
      molecularWeight: 98.08,
      smiles: "OS(=O)(=O)O",
      chemicalFormula: "H2SO4",
      CASNumber: "7664-93-9",
      supplier: "Fisher Scientific",
      purity: 0.98,
    }),

    new Reagent({
      id: "R-019",
      type: "reagent",
      name: "phosphoric acid",
      created: CREATED,
      density: 1.685,
      alias: "H3PO4",
      costPerGram: 0.0012,
      costUnit: "$",
      state: "liquid",
      description: "Orthophosphoric acid, 85% w/w aqueous solution",
      hazards: ["H290", "H314"],
      molecularWeight: 97.99,
      smiles: "OP(=O)(O)O",
      chemicalFormula: "H3PO4",
      CASNumber: "7664-38-2",
      supplier: "Sigma-Aldrich",
      purity: 0.85,
    }),

    new Reagent({
      id: "R-020",
      type: "reagent",
      name: "glycerol",
      created: CREATED,
      density: 1.261,
      alias: "glycerin",
      costPerGram: 0.0006,
      costUnit: "$",
      state: "liquid",
      description: "Glycerol, pharmaceutical grade",
      hazards: [],
      molecularWeight: 92.09,
      smiles: "OCC(O)CO",
      chemicalFormula: "C3H8O3",
      CASNumber: "56-81-5",
      supplier: "Merck",
      purity: 0.99,
    }),
  ]
}
